[InvitationMessageText]
description = ""
one = "あなたの招待コードは{{.Code}}です。グループへの参加はこのコードをお使いください。"
other = "あなたの招待コードは{{.Code}}です。グループへの参加はこのコードをお使いください。"

[WelcomeMessageTitle]
description = ""
one = "ようこそ、{{.Name}}さん"
other = "ようこそ{{.Name}}さん"

[WelcomeMessageDescription]
description = ""
one = "タップしてガイドラインを読む"
other = "タップしてガイドラインを読む"

[GroupModeLectureMessage]
description = ""
one = "{{.Name}}さんがレクチャーモードに切り替わりました。"
other = "{{.Name}}さんがレクチャーモードに切り替わりました。"

[GroupModeMuteMessage]
description = ""
one = "{{.Name}}さんがミュートモードに切り替わりました。"
other = "{{.Name}}さんがミュートモードに切り替わりました。"

[GroupModeFreeMessage]
description = ""
one = "{{.Name}}さんが雑談モードに切り替わりました。"
other = "{{.Name}}さんが雑談モードに切り替わりました。"

[LuckycoinTitle]
description = ""
one = "グループのラッキーコイン"
other = "グループのラッキーコイン"

[LuckycoinDescription]
description = ""
one = "{{.Name}}さんから"
other = "{{.Name}}さんへ"

[LuckycoinOpenedMessage]
description = ""
one = "{{.Name}}さんがあなたのラッキーコインを開封しました。"
other = "{{.Name}}さんがあなたのラッキーコインを開封しました。"

[BroadcastOnMessage]
description = ""
one = "ストリーミングオン"
other = "ストリーミングオン"

[BroadcastOffMessage]
description = ""
one = "ストリーミングオフ"
other = "ストリーミングオフ"

[AnnouncementMessage]
description = ""
one = "アナウンス: {{.Text}}"
other = "アナウンス: {{.Text}}"

[PublicJoinMessage]
description = ""
one = "{{.Name}}さんがグループに参加しました。"
other = "{{.Name}}さんがグループに参加しました。"

[JoinMessage]
description = ""
one = "グループに参加しました。"
other = "グループに参加しました。"

[JoinInMuteModeMessage]
description = ""
one = "グループに参加しましたが、ミュートモードのためあなたは話すことができません。"
other = "グループに参加しましたが、ミュートモードのためあなたは話すことができません。"

[JoinInstructionMessage]
description = ""
one = "ここはプライベートグループです。ボタンをタップして参加し、「始める」をタップして詳しい情報を確認して下さい。"
other = "ここはプライベートグループです。ボタンをタップして参加し、「始める」をタップして詳しい情報を確認して下さい。"

[JoinInstructionEntryMessage]
description = ""
one = "タップして参加する"
other = "タップして参加する"

[JoinGuideMessageTitle]
description = ""
one = "始める"
other = "始める"

[JoinGuideMessageDescription]
description = ""
one = "タップしてガイドを読む"
other = "タップしてガイドを読む"

[AdminRenewMessage]
description = ""
one = "{{.Name}}さんがメンバーシップを更新しました。"
other = "{{.Name}}さんがメンバーシップを更新しました。"

[RenewMessage]
description = ""
one = "メンバーシップを更新しました。"
other = "メンバーシップを更新しました。"

[MsgToLongMessage]
description = ""
one = "送信失敗。メッセージが長すぎます。"
other = "送信失敗。メッセージが長すぎます。"

[UnsubscribedMessage]
description = ""
one = "メンバーシップを解除したため、メッセージの送信/受信はもうできません。"
other = "メンバーシップを解除したため、メッセージの送信/受信はもうできません。"

[ChatRateLimitMessage]
description = ""
one = "メッセージが多すぎます。"
other = "メッセージが多すぎます。"

[TipMessage]
description = ""
one = "{{.From}}さんが{{.To}}さんへ{{.Amount}}{{.Symbol}}を送金しました。"
other = "{{.From}}さんが{{.To}}さんへ{{.Amount}}{{.Symbol}}を送金しました。"


[InvitationCreateMessage]
description = ""
one = "{{.Num}} 招待コードが発行されました。\"招待 - 私の招待コード\"から確認して下さい。"
other = "{{.Num}} 招待コードが発行されました。\"招待 - 私の招待コード\"から確認して下さい。"

[WritingClassCouponClaimedMessage]
description = "写作课 500 元抵扣券发放后给用户发的消息"
one = "你获得了一张写作课 {{.Amount}} 元优惠券，请打开“群首页 - 优惠券”查看"
other = "你获得了一张写作课 {{.Amount}} 元优惠券，请打开“群首页 - 优惠券”查看"

[RenewNotifyMessage]
description = ""
one = "あなたのメンバーシップは{{.Date}}で期限切れです。メンバーシップを更新して下さい。"
other = "あなたのメンバーシップは{{.Date}}で期限切れです。メンバーシップを更新して下さい。"

[BindInvitationNotifyMessage]
description = ""
one = "あなたはこのグループに招待されています。ボタンをタップして参加してください。"
other = "あなたはこのグループに招待されています。ボタンをタップして参加してください。"
